version: "3.8"

services:
  traefik:
    image: "traefik:v2.8"
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.http.address=:80"
      - "--providers.docker=true"  # Використовуємо Docker як джерело конфігурації
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
    ports:
      - "80:80"  # Порт для HTTP
      - "8080:8080"  # Панель управління Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Для доступу до Docker API
      - ./dynamic.yml:/etc/traefik/dynamic.yml  # Для динамічної конфігурації
    networks:
      - symfony_net
#      - laba1_net
#      - laba2_net
    labels:
      - "traefik.enable=true"

#networks:
#  laba_net:
#    name: laba_net
#    driver: bridge

networks:
  symfony_net:
    external: true
#  laba2_net:
#    external: true

